name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pynput

    - name: Build exe folder
      run: |
        pyinstaller --windowed --name SpeedrunTimer main.py

    - name: Upload build folder
      uses: actions/upload-artifact@v4
      with:
        name: SpeedrunTimer
        path: dist/SpeedrunTimer/
